### ISSUE TITLE
How to call contract action?

### ISSUE THREAD

**Issue by shtse8** [SNIKO/eosnet#2]
Any demo code to call contract action? thanks.

**Comment by SNIKO** [comment]
Added examples to the main page. The new NuGet package will be available soon.

**Comment by shtse8** [comment]
@SNIKO  Thanks for the update. By the way, any more example on how to get table rows from the block chain?

**Comment by shtse8** [comment]
I have figured it out myself.

```C#
var response = await _eosClient.Api.GetTableRowsAsync(new TableQuery()
	{
		Code = account,
		Limit = 100,
		LowerBound = id,
		Scope = account,
		Table = tableName
	});
``
