### ISSUE TITLE
Error occur sometimes when pushing actions

### ISSUE THREAD

**Issue by shtse8** [SNIKO/eosnet#3]
```
 Error converting value "3063e3af2ed3b038e2f7db7cb7d9146f5a24ffa4a392e8a36e73071d66767393" to type 'EOS.Client.Models.SignedTransaction'. Path 'transactions[0].trx', line 1, position 667.
 Newtonsoft.Json.JsonSerializationException: Error converting value "3063e3af2ed3b038e2f7db7cb7d9146f5a24ffa4a392e8a36e73071d66767393" to type 'EOS.Client.Models.SignedTransaction'. Path 'transactions[0].trx', line 1, position 667. ---> System.ArgumentException
: Could not cast or convert from System.String to EOS.Client.Models.SignedTransaction.
```

**Comment by shtse8** [comment]
After deep investigation, the error is thrown from here:
https://github.com/SNIKO/eosnet/blob/master/src/EOS.Client/EosClient.cs#L30

Also, the ref_block_prefix can calculated from the block hash. So we can save one request for sending action. And also, we should use last irreversible block instead of head block.

Here is my modified code: (BTW, I am using dependency.)
```C#
public async Task<string> PushActionsAsync(IEnumerable<EOS.Client.Models.Action> actions)
        {
            
            var chainInfo = await _eosClient.Api.GetInfoAsync();
            var refBlockPrefix = BitConverter.ToUInt32(chainInfo.LastIrreversibleBlockId.ToByteArray(StringEncoding.Hex).SafeSubarray(8, 4));
            var transaction = new Transaction
            {
                RefBlockNum = chainInfo.LastIrreversibleBlockNum,
                RefBlockPrefix = refBlockPrefix,
                Expiration = chainInfo.HeadBlockTime.AddSeconds(60),
                Actions = actions
            };

            return await _eosClient.PushTransactionAsync(transaction);
        }
```     
I suggest to use [SimpleBase](https://github.com/ssg/SimpleBase) for doing base32 and base58 conversion. It is a good package.

**Comment by SNIKO** [comment]
Yeah, there are plenty of things that can be optimized. Plus we need proper errors handling. The current implementation is just to start. Thanks for your comments. 

Do you have an example of the transaction causing the issue? Want node or BP you connect to? They break API all the time and something that worked a month ago doesn't work now.

**Comment by shtse8** [comment]
I am using my private node due to the public nodes are mostly unstable.

My action is just calling my contract (still in developing on testnet) with some parameters. So I don't know how to provide some example for you to test. :(

**Comment by SNIKO** [comment]
The problem is in GetBlockAsync which is called when you call PushActionAsync. I use it to get info about the last block. A block contains a list of transactions which supposed to be in plain json but looks like in some cases it returns encoded transactions which then I try to deserialize as json and fail.

A workaround would be to use PushTransactionAsync and avoid calling GetBlockAsync.

I need to decode transactions if they come encoded (deserialization logic has to be implemented) or, as a fast solution, return an object which is either SignedTransaction object or a hex string (encoded transaction).

**Comment by SNIKO** [comment]
Yeah, a block contains either transaction itself or transaction id. I've updated the converter so that it supports both. Should be fine now.
